#!/usr/bin/env bash
#SBATCH -p cpu20
#SBATCH -t 8:00:00
#SBATCH -c 8
#SBATCH --mem=32G
#SBATCH -o /BS/dniazi_thesis/work/RandomizedSmothingmanifold/output/slurm/rococo-index-%j.out
#SBATCH -e /BS/dniazi_thesis/work/RandomizedSmothingmanifold/output/slurm/rococo-index-%j.err
#SBATCH -J rococo-index

# =============================================================================
# Build Annoy kNN index on CLIP image embeddings (512-dim, angular metric).
# Requires: embeddings already generated by submit_rococo_embeddings.sh
# =============================================================================

set -euo pipefail
PROJECT_ROOT="/BS/dniazi_thesis/work/RandomizedSmothingmanifold"
cd "$PROJECT_ROOT"
mkdir -p output/slurm

if [[ -f "/BS/dniazi_thesis/work/miniforge3_new/etc/profile.d/conda.sh" ]]; then
    source "/BS/dniazi_thesis/work/miniforge3_new/etc/profile.d/conda.sh"
    conda activate smoothing
fi

echo "Running on: $(hostname)"

REBUILD=""
[[ "${1:-}" == "--rebuild" ]] && REBUILD="--rebuild"

python -m src.experiments.indexing.rococo_clip_images \
    --config src/configs/experiments/rococo_clip_manifold.yaml \
    $REBUILD
